version: "2"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: movie_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.15.0
  #   container_name: movie_kib
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://movie_es:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elastic

  app:
    build: .
    container_name: semantic_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./huggingface_cache:/huggingface_cache
    depends_on:
      - elastic
    environment:
      - HF_HOME=/huggingface_cache
      - TRANSFORMERS_OFFLINE=1

